### ISSUE TITLE
i don't understand why result is outside of the loop. please explain thanks! 

### ISSUE THREAD

**Issue by geekidharsh** [lamphanviet/hackerrank-python#1]
https://github.com/lamphanviet/hackerrank-python/blob/06ae0a1977a3cd75ef1275e1bb2957e8474d92ac/sherlock-and-anagrams.py#L17

**Comment by lamphanviet** [comment]
Hmm, I could be a display issue from your side.

I review the code here and looks like that line is still part of the second for loop. https://github.com/lamphanviet/hackerrank-python/blob/06ae0a1977a3cd75ef1275e1bb2957e8474d92ac/sherlock-and-anagrams.py#L17

Can you double check?
